Repository micronaut-projects/micronaut-test, pull requests merged in 2020-09, with the labels that each got.

#275 Dependency upgrades
  test-junit5/build.gradle
Labels: type: dependency-upgrade

#273 [test] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#274 [test] Update common files for branch 1.2.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#289 [test] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#290 [test] Update common files for branch 1.2.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#162 Upgrade to Micronaut 2.x
  gradle.properties
  test-core/build.gradle
  test-junit5/build.gradle
  test-kotest/build.gradle
  test-kotlintest/build.gradle
  test-spock/build.gradle
Labels: type: dependency-upgrade, type: enhancement

#283 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade
