Repository micronaut-projects/micronaut-test, pull requests merged in 2020-10, with the labels that each got.

#301 Dependency upgrades
  gradle.properties
  test-junit5/build.gradle
Labels: type: dependency-upgrade

#308 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#309 [test] Update common files for branch master
  .github/workflows/bintray-publish.yml
Labels: relates-to: build

#311 [test] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#312 [test] Update common files for branch 2.0.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#316 Allow Micronaut Test to run against an external server
  gradle.properties
  test-core/build.gradle
  test-core/src/main/java/io/micronaut/test/support/server/TestEmbeddedServer.java
  test-junit5/src/test/java/io/micronaut/test/junit5/server/ExternalServerTest.java
Labels: type: enhancement
