Repository micronaut-projects/micronaut-test, pull requests merged in 2023-06, with the labels that each got.

#775 [test] Update common files for branch master
  .github/renovate.json
Labels: relates-to: build

#782 [test] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build

#784 Add to the text context: test name and if the test method interceptor is supported
  test-core/src/main/java/io/micronaut/test/context/TestContext.java
  test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java
  test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java
  test-kotest5/src/main/kotlin/io/micronaut/test/extensions/kotest5/MicronautKotest5Context.kt
  test-kotest5/src/test/kotlin/io/micronaut/test/kotest5/intercept/InterceptTest.kt
  test-kotest5/src/test/kotlin/io/micronaut/test/kotest5/intercept/TestInterceptor.kt
  test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java
Labels: type: improvement

#792 ci: checkout workflow to 3.5.3 slsa 1.7.0
  .github/workflows/release.yml
Labels: relates-to: build

#798 Test to core 4.0.0-RC1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
