Repository micronaut-projects/micronaut-test, pull requests merged in 2023-04, with the labels that each got.

#742 [test] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#745 Upgrade to Kotest 5.6.0
  gradle/libs.versions.toml
Labels: status: next major version

#747 Update settings plugin
  gradle/libs.versions.toml
  settings.gradle
Labels: relates-to: build

#733 build: enable testNative
  test-junit5/build.gradle
Labels: relates-to: graal

#754 Add dynamic registration of test property providers
  test-core/build.gradle
  test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java
  test-core/src/main/java/io/micronaut/test/support/TestPropertyProviderFactory.java
  test-core/src/testFixtures/java/io/micronaut/test/core/fixtures/DummyTestPropertyProvider.java
  test-core/src/testFixtures/java/io/micronaut/test/core/fixtures/DummyTestPropertyProviderFactory.java
  test-core/src/testFixtures/resources/META-INF/services/io.micronaut.test.support.TestPropertyProviderFactory
  test-junit5/build.gradle
  test-junit5/src/test/java/io/micronaut/test/junit5/props/TestPropertyProviderFactoryTest.java
  test-junit5/src/test/resources/application-testenv1.yml
  test-kotest5/build.gradle
  test-kotest5/src/test/kotlin/io/micronaut/test/kotest5/TestPropertiesFactoryCtorInjectionTest.kt
  test-kotest5/src/test/kotlin/io/micronaut/test/kotest5/TestPropertiesFactoryTest.kt
  test-spock/build.gradle
  test-spock/src/test/groovy/io/micronaut/test/spock/props/TestPropertiesProviderFactoryTest.groovy
Labels: type: improvement
