Repository micronaut-projects/micronaut-test, pull requests merged in 2024-02, with the labels that each got.

#948 Testcontainers via test-resources version catalog
  gradle/libs.versions.toml
  settings.gradle
  test-suite-at-sql-jpa/build.gradle.kts
  test-suite-sql-r2dbc/build.gradle.kts
Labels: relates-to: build

#935 [test] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#951 fix: TestSqlAnnotationHandler fails if context stopped in test
  test-core/src/main/java/io/micronaut/test/support/sql/TestSqlAnnotationHandler.java
  test-junit5/src/test/java/io/micronaut/test/junit5/ApplicationStopTest.java
  test-junit5/src/test/java/io/micronaut/test/junit5/SqlDatasourceApplicationStopTest.java
Labels: type: bug

#950 [test] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#953 fix: add interceptor around parameterized features
  test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java
  test-spock/src/test/groovy/io/micronaut/test/spock/intercept/InterceptTestSpec.groovy
Labels: lang: groovy, type: bug

#954 fix: add interceptor around parameterized features (#953)
  test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java
  test-spock/src/test/groovy/io/micronaut/test/spock/intercept/InterceptTestSpec.groovy
Labels: lang: groovy, type: bug

#957 Mention the annotation config when misconfigured
  test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java
Labels: type: docs
